services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    volumes:
      - ./auth_info:/usr/src/app/auth_info   # Solo montamos la sesión
    command: npm start
    tty: true   # Para que el QR se imprima correctamente en terminal
